"""Specification generation from a known-good recording.

Writing a spec by hand requires knowing every topic name and its nominal rate
up front. Generating one from a recording that is already trusted inverts that:
record a good run, generate, then validate everything afterwards against it.
"""

from __future__ import annotations

from pathlib import Path

from baglint.checks.base import TopicStat
from baglint.runner import scan

# Observed timing is one sample of a noisy process, so the generated bounds are
# deliberately slack. Tighten them by hand once you know the real variance.
DEFAULT_MARGIN = 0.10
GAP_MULTIPLIER = 2.0

# Below this many messages a mean rate says more about the recording length
# than about the publisher, so the topic is generated as presence-only.
MIN_SAMPLES_FOR_RATE = 10


def _round(value: float) -> float:
    """Keep generated numbers readable rather than carrying full precision."""
    if value >= 100:
        return round(value)
    if value >= 1:
        return round(value, 1)
    return round(value, 3)


def _topic_block(stat: TopicStat, margin: float) -> list[str]:
    lines = [f"  {stat.topic}:"]

    rate = stat.rate_hz
    if rate is not None and stat.count >= MIN_SAMPLES_FOR_RATE:
        lines.append(f"    min_rate: {_round(rate * (1.0 - margin))}")
        lines.append(f"    max_gap_ms: {_round(stat.max_interval_ms * GAP_MULTIPLIER)}")
    else:
        lines.append(f"    # {stat.count} message(s); presence only")

    return lines


def generate_spec(path: str | Path, margin: float = DEFAULT_MARGIN) -> str:
    """Return a spec, as YAML text, describing the recording at `path`."""
    result = scan(path)
    stats = result.ctx.stats

    header = [
        f"# Generated by baglint --init from {Path(path).name}",
        f"# {result.topic_count} topics, {result.message_count:,} messages, "
        f"{result.ctx.duration_s:.1f} s",
        "#",
        f"# min_rate is {margin:.0%} below the observed mean rate; max_gap_ms is "
        f"{GAP_MULTIPLIER:g}x the worst",
        "# observed interval. Both are starting points -- adjust them to the",
        "# tolerance the recording actually needs.",
        "",
    ]

    if not stats:
        return "\n".join(header + ["topics: {}", ""])

    body = ["topics:"]
    for topic in sorted(stats):
        body += _topic_block(stats[topic], margin)
        body.append("")

    return "\n".join(header + body)
